# todo auto add dep to lokiConfig

function(loki_find_dep depName depVer depComps)
  if (${depName}_DIR)
    message("\"${depName}_DIR\" found! Value is \"${${depName}_DIR}\"")
    find_package(${depName} ${depVer} COMPONENTS "${depComps}" CONFIG PATHS "${${depName}_DIR}" NO_DEFAULT_PATH)
    if (NOT ${depName}_FOUND)
      list(APPEND LOKI_DEP_ERROR_LIST "${depName}")
    endif ()
  else ()
    message("\"${depName}_DIR\" not found! Trying to find it anyway!")
    find_package(${depName} ${depVer} COMPONENTS "${depComps}" CONFIG)
    if (NOT ${depName}_FOUND)
      list(APPEND LOKI_DEP_ERROR_LIST "${depName}")
    endif ()
  endif ()
  loki_print_variables_with_pattern(${depName})
  set(LOKI_DEP_ERROR_LIST "${LOKI_DEP_ERROR_LIST}" PARENT_SCOPE)
endfunction()

function(loki_find_all_deps depList)
  set(LOKI_DEP_ERROR_LIST "")
  foreach (dep ${depList})
    string(REPLACE "," ";" depData ${dep})
    list(LENGTH depData depDataLen)
    list(GET depData 0 depName)
    string(STRIP ${depName} depName)
    list(GET depData 1 depVer)
    string(STRIP ${depVer} depVer)
    if (depDataLen GREATER 2)
      list(GET depData 2 depComps)
      string(STRIP ${depComps} depComps)
      string(REPLACE " " ";" depComps ${depComps})
    endif ()
    loki_find_dep(${depName} ${depVer} "${depComps}")
  endforeach ()
  foreach(LOKI_DEP_ERROR ${LOKI_DEP_ERROR_LIST})
    message(SEND_ERROR "${LOKI_DEP_ERROR} not found! Please set ${LOKI_DEP_ERROR}_DIR (current value is \"${${LOKI_DEP_ERROR}_DIR}\").")
  endforeach()
endfunction()
