set(LOKI_LOG_CMAKE_CONFIG ON CACHE BOOL "Log useful information ")

include(CMakePrintHelpers)
function(loki_print_variables_with_pattern pattern)
    if(LOKI_LOG_CMAKE_CONFIG)
        get_cmake_property(_variableNames VARIABLES)
        list (SORT _variableNames)
        foreach (_variableName ${_variableNames})
            unset(MATCHED)
            string(REGEX MATCH ${pattern} MATCHED ${_variableName})
            if (NOT MATCHED)
                continue()
            endif()
            cmake_print_variables(${_variableName})
        endforeach()
    endif()
endfunction()

function(loki_print_variables)
    if(LOKI_LOG_CMAKE_CONFIG)
        cmake_print_variables(${ARGV})
    endif()
endfunction()