name: build

# Inspired by SFML's ci.yml

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review 

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    name: ${{ matrix.platform.os }} ${{ matrix.platform.compiler.name }} ${{ matrix.platform.compiler.version }}
    runs-on: ${{ matrix.platform.os }}

    env:
      matrix-key: ${{ matrix.platform.os }}-${{ matrix.platform.compiler.name }}-${{ matrix.platform.compiler.version }}
    #  # Use ccache to cache C/C++ compiler output
    #  CMAKE_C_COMPILER_LAUNCHER: ccache
    #  CMAKE_CXX_COMPILER_LAUNCHER: ccache

    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: windows-2025
            compiler: { name: MSVC, version: '19.44', msvc-toolset: '14.44', c-exe: cl, cpp-exe: cl }
          - os: windows-2025
            compiler: { name: ClangCL, version: '19.1', msvc-toolset: '14.44', cmake-toolset: ClangCL }
          - os: windows-2025
            compiler: { name: Clang, version: '21.1', c-exe: clang, cpp-exe: clang++ }
          - os: windows-2025
            compiler: { name: GCC, version: '15.2', c-exe: gcc, cpp-exe: g++ }
          - os: ubuntu-24.04
            compiler: { name: GCC, version: '15.2', c-exe: gcc, cpp-exe: g++, conda-cpp-exe: gxx }
          - os: ubuntu-24.04
            compiler: { name: Clang, version: '21.1', c-exe: clang, cpp-exe: clang++, conda-cpp-exe: clangxx }

    steps:
      # Code
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # Common Tools
      - name: Get CMake and Ninja
        uses: lukka/get-cmake@v4.1.2
        with:
          cmakeVersion: '4.1.2'
          ninjaVersion: latest

      #- name: Setup CCache
      #  # In addition to installing a known working version of CCache, this action also takes care of saving and restoring the cache for us
      #  # Additionally it outputs information at the end of each job that helps us to verify if the cache is working properly
      #  uses: hendrikmuhs/ccache-action@v1.2.19
      #  with:
      #    verbose: 2
      #    key: ${{ env.matrix-key }}-ccache

      # Compilers
      - name: Set up MSVC toolchain
        if: matrix.platform.compiler.msvc-toolset
        uses: TheMrMilchmann/setup-msvc-dev@v4.0.0
        with:
          arch: x64
          toolset: ${{ matrix.platform.compiler.msvc-toolset }}

      - name: Install WinLibs GCC
        id: winlibs-gcc
        if: matrix.platform.os == 'windows-2025' && matrix.platform.compiler.name == 'GCC'
        uses: bwoodsend/setup-winlibs-action@v1.16
        with:
          architecture: '64'
          runtime: ucrt
          threads: posix
          with_clang: false
          add_to_path: true

      - name: Use WinLibs GCC
        if: matrix.platform.os == 'windows-2025' && matrix.platform.compiler.name == 'GCC'
        run: |
          echo "CC=${{ steps.winlibs-gcc.outputs.bin }}/gcc" >> $GITHUB_ENV
          echo "CXX=${{ steps.winlibs-gcc.outputs.bin }}/g++" >> $GITHUB_ENV

      - name: Install and use LLVM Clang on Windows
        if: matrix.platform.os == 'windows-2025' && matrix.platform.compiler.name == 'Clang'
        uses: KyleMayes/install-llvm-action@v2.0.8
        with:
          version: ${{ matrix.platform.compiler.version }}
          env: true

      # - name: Cache conda setup
      #   if: matrix.platform.os == 'ubuntu-24.04'
      #   uses: actions/cache@v4.3.0
      #   with:
      #     path: ~/conda_pkgs_dir
      #     key: ${{ env.matrix-key }}-conda

      - name: Setup miniconda on Linux
        if: matrix.platform.os == 'ubuntu-24.04'
        uses: conda-incubator/setup-miniconda@v3.2.0
        with:
          miniforge-variant: Miniforge3
          miniforge-version: '25.9.1-0'
          activate-environment: build
          channels: conda-forge
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true
          # use-only-tar-bz2: true # needed for cache
          architecture: x64

      - name: Install and use compiler on Linux
        if: matrix.platform.os == 'ubuntu-24.04'
        run: |
          conda install -qy ${{ matrix.platform.compiler.c-exe }}=${{ matrix.platform.compiler.version }} ${{ matrix.platform.compiler.conda-cpp-exe }}=${{ matrix.platform.compiler.version }}
          echo "CC=$CONDA/envs/build/bin/${{ matrix.platform.compiler.c-exe }}" >> $GITHUB_ENV
          echo "CXX=$CONDA/envs/build/bin/${{ matrix.platform.compiler.cpp-exe }}" >> $GITHUB_ENV

      # Dependencies
      - name: Install SFML Linux dependencies
        if: matrix.platform.os == 'ubuntu-24.04'
        run: conda install -qy freetype libflac libfreetype libglx-devel libopengl-devel libogg libpng libudev libvorbis libzlib mesa-libegl-devel-cos7-x86_64 mesa-libgbm-cos7-x86_64 mesa-libgl-devel-cos7-x86_64 mesalib openal-soft pthread-stubs xorg-libx11 xorg-libxcursor xorg-libxrandr

      # Build
      - name: Create build folder
        run: mkdir build-${{ env.matrix-key }}

      - name: Configure CMake
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build-${{ env.matrix-key }} -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install-${{ env.matrix-key }} ${{ (matrix.platform.compiler.cmake-toolset && format('-T {0}', matrix.platform.compiler.cmake-toolset)) || '-G Ninja' }}

      - name: Build
        run: cmake --build $GITHUB_WORKSPACE/build-${{ env.matrix-key }} --config Debug --target install
