name: check-cmake-format

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-format:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: PuneetMatharu/cmake-format-lint-action@v1.0.0
        with:
          args: --check
