name: check-format

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-format:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: 'src/loki'
          extensions: 'hpp,hxx,cpp'
          clangFormatVersion: 13
          style: file
      - uses: PuneetMatharu/cmake-format-lint-action@v1.0.0
        with:
          args: --check
