name: Test

on: pull_request

jobs:
  build:
    name: ${{ matrix.cc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        cc: [gcc, clang]
        include:
          - os: windows-latest
            cc: cl
          - os: macos-latest
            cc: clang

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install
          libsfml-dev
          libfmt-dev
          nlohmann-json3-dev


      - name: Install Android Components
        if: matrix.platform.name == 'Android'
        run: |
          echo "y" | /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "cmake;3.10.2.4988404" --sdk_root=ANDROID_SDK_ROOT
          sudo ln -sf /usr/local/lib/android/sdk/cmake/3.10.2.4988404/bin/cmake /usr/bin/cmake
          wget -nv https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip -P $GITHUB_WORKSPACE
          unzip -qq -d $GITHUB_WORKSPACE android-ndk-r18b-linux-x86_64.zip
      - name: Configure CMake
        shell: bash
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DSFML_BUILD_TEST_SUITE=TRUE ${{matrix.platform.flags}} ${{matrix.config.flags}}

      - name: Build
        shell: bash
        run: cmake --build $GITHUB_WORKSPACE/build --config Release --target install
